### ISSUE TITLE
ability to send additional query params to edit page

### ISSUE THREAD

**Issue by moyesm** [cbcrc/koco-content-management#4]
Because our project deals with translations, our api endpoint now requires a localeId to be passed with the get/post request, ie ... api/resource/edit/1?localeId=2.
This is trivial on the list page, which already handles extra params to support searching.
However, I'd like to edit the `content-edit-page-base-viewmodel` to accept params as well.
I was thinking when we're implementing, we could just add a property to the view model, ex:

```
            self.apiCriteria = {
                localeId: wamApi.user().localeId
            };
```

and then modify `content-edit-page-base-viewmodel`'s `loadContentInner` method like so:

```
        function loadContentInner(self, id, dfd) {
            var dataParams = null;

            if (self.apiCriteria) {
                dataParams = { data: $.param(self.apiCriteria, true) };
            }

            if (id) {
                self.api.getJson(self.apiResourceName + '/' + id,
                        function(content) {
                            ...
                        },
                        dataParams)
                    .fail(function(jqXHR, textStatus, errorThrown) {
...
        }
```

If that sounds good, let me know; of I'd be happy to hear other ideas for implementing this.

**Comment by RCMax** [comment]
Good idea! I guess we can add this without breaking the API (additive change, so we don't have to create another major/minor version)?

**Comment by moyesm** [comment]
Added in v0.1.26
