### ISSUE TITLE
Output unknown error message by default?

### ISSUE THREAD

**Issue by moyesm** [cbcrc/koco-content-management#5]
Right now, handleUnknownError is an empty function that can be overridden. I think it might be worth outputting something by default, just so the error doesn't get swallowed.

```
var defaultSettings = {
            unknownErrorMessage: 'Une erreur de type inconnu est survenu: ',
... 
       ContentEditPageBaseViewModel.prototype.handleUnknownError = function(jqXhr, textStatus, errorThrown) {
            var self = this;
            toastr.error(self.settings.unknownErrorMessage + errorThrown);

        };
```

But I thought I'd check whether this was a deliberate design choice first... Let me know what you think.

**Comment by RCMax** [comment]
I think you are right

**Comment by moyesm** [comment]
Added in 0.1.27
