### ISSUE TITLE
Why is loadContent called after onUpdateSuccess ?

### ISSUE THREAD

**Issue by th3answer** [cbcrc/koco-content-management#6]
I'm trying to understand why it is required to reload the content from the server each time we update some data. In other word is it really necessary to make an api call after each save ?
see line 492  : 

``` javascript
ContentEditPageBaseViewModel.prototype.onUpdateSuccess = function(id, dfd /*, data, textStatus, jqXhr*/ ) {
            var self = this;

            toastr.success(self.settings.contentUpdatedMessage);
            self.loadContent(id, dfd); // this is the extra api call

           // I suggest we resolve the promise here
           // dfd.resolve()
        };
```

**Comment by fcharest** [comment]
Sometimes, the server will do some logic in the saving process and values may have changed depending on said logic. I don't have specific examples of this though.

However, you could override the method and just omit loadContent() altogether if it makes more sens in the way your API is built.

**Comment by th3answer** [comment]
@fcharest Thanks, I'll just override this behavior.
